[workspace]
members = ["common"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["448-OG <superuser@448.africa>"]
license = "Apache-2.0 OR MIT"
description = "Solana Client Framework"

[workspace.dependencies]
